### ISSUE TITLE
[8.0] sale_order_add_variants  -Not all variant's product unit price is generated in the order lines

### ISSUE THREAD

**Issue by bunhin** [OCA/sale-workflow#330] opened 2016-08-12 02:53 UTC
i created a product with Size as attribute and have 6 size value, and Product_variant_default_code module from odoomrp-wip is installed. The variants and the code successfully created complete with the unit price. Then create sales quotation and select customer, and price list to be used then click add variants button in top-left, select the product template and input quantity for each variant then click add to order button.

6 order lines was generated with the quantity but for product-unit price, 2 lines of variants has zero unit price (line #3 and line #5 of  6 lines)

Then I uninstall all module related to variants except the product_variant_default_code, and then reinstall the sale_order_add_variants and repeat the process,  the problem still happen.

Please help

**Comment by pedrobaeza** [comment] 2017-03-21 07:55
@hugosantosred can you help with this issue?

**Comment by hugosantosred** [comment] 2017-03-21 15:15
@bunhin I couldn't reproduce the bug.

I've tried with a template with 4 variants, some of them has a pricelist item defined, when I select that template and add units of the variants with the "Add Variants" button in the sale order, the prices are the same that are defined in the pricelist.

Do you have instaled any module to change the behaviour of prices on variants? The customer pricelist has a default line for items standard price, like the one in the public pricelist?

**Comment by pedrobaeza** [comment] 2017-03-21 15:18
Closing then until further notice.

**Closed as completed by pedrobaeza** 2017-03-21 15:18 UTC
