### ISSUE TITLE
Odoo 10 installation fail

### ISSUE THREAD

**Issue by wangsamas** [OCA/sale-workflow#546] opened 2017-10-11 18:03 UTC
Hi, I get this error

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/tools/convert.py", line 845, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/tools/convert.py", line 915, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/tools/convert.py", line 799, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/tools/convert.py", line 707, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/addons/base/ir/ir_model.py", line 1190, in _update
    record.write(values)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/addons/sale_rental/models/stock.py", line 149, in write
    self.env[obj].create(rule)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/models.py", line 3826, in create
    record = self.browse(self._create(old_vals))
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/models.py", line 3906, in _create
    self._check_selection_field_value(name, val)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/models.py", line 2125, in _check_selection_field_value
    field.convert_to_cache(value, self)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/fields.py", line 1740, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ParseError: "Wrong value for stock.location.path.auto: 'auto'" while parsing /opt/bitnami/apps/odoo/lib/odoo-10.0.post20170915-py2.7.egg/odoo/addons/sale_rental/data/rental_data.xml:22, near
`<record id="stock.warehouse0" model="stock.warehouse">
    <field name="rental_allowed" eval="True"/>
</record>`
 what should I do?
thx

**Comment by pedrobaeza** [comment] 2018-04-05 15:18
This seems to be something related to the deployment, as the module is installed in runbot without problems. Please try to reproduce the problem in runbot:

https://runbot.odoo-community.org/runbot/167/10.0

and report back.

Meanwhile, I close this.

**Closed as completed by pedrobaeza** 2018-04-05 15:18 UTC
